const loginFormActionTypes = {
    CHANGE_EMAIL_STATE:"CHANGE_EMAIL_STATE",
    CHANGE_PASSWORD_STATE:"CHANGE_PASSWORD_STATE",
    CHANGE_FORM_MESSAGE_STATE:"CHANGE_FORM_MESSAGE_STATE",
    CHANGE_SHOW_ERROR_MESSAGES:"CHANGE_SHOW_ERROR_MESSAGES",
}

export default loginFormActionTypes;