export const PPRSecondFormActionTypes = {
    CHANGE_ESTATE_TYPE_STATE:"CHANGE_ESTATE_TYPE_STATE",
    CHANGE_ESTATE_CONDITION_STATE:"CHANGE_ESTATE_CONDITION_STATE",
    CHANGE_CITY_STATE:"CHANGE_CITY_STATE",
    CHANGE_STREET_STATE:"CHANGE_STREET_STATE",
    CHANGE_NUMBER_STATE:"CHANGE_NUMBER_STATE",
    CHANGE_FLOOR_STATE:"CHANGE_FLOOR_STATE",
    CHANGE_TOTAL_FLOORS_STATE:"CHANGE_TOTAL_FLOORS_STATE",
    CHANGE_ON_PILLARS_STATE:"CHANGE_ON_PILLARS_STATE",
    CHANGE_MAILING_LIST_STATE:"CHANGE_MAILING_LIST_STATE",
    CHANGE_SHOW_ERROR_STATE:"CHANGE_SHOW_ERROR_STATE",
    CHANGE_COMPLETED_STATE:"CHANGE_COMPLETED_STATE",
}

export const PPRThirdFormActionTypes = {
    CHANGE_ROOMS_STATE:"CHANGE_ROOMS_STATE",
    CHANGE_PARKING_STATE:"CHANGE_PARKING_STATE",
    CHANGE_BALCONIES_STATE:"CHANGE_BALCONIES_STATE",
    CHANGE_FEATURES_STATE:"CHANGE_FEATURES_STATE",
    CHANGE_DESCRIPTION_STATE:"CHANGE_DESCRIPTION_STATE",
    CHANGE_SHOW_ERROR_STATE:"CHANGE_SHOW_ERROR_STATE",
    CHANGE_COMPLETED_STATE:"CHANGE_COMPLETED_STATE",
}