export const PPRFormActionsTypes = {
    CHANGE_FIRST_FORM_VALUES:"CHANGE_FIRST_FORM_VALUES",
    CHANGE_SECOND_FORM_VALUES:"CHANGE_SECOND_FORM_VALUES",
    CHANGE_THIRD_FORM_VALUES:"CHANGE_THIRD_FORM_VALUES",
    CHANGE_FOURTH_FORM_VALUES:"CHANGE_FOURTH_FORM_VALUES",
    CHANGE_FIFTH_FORM_VALUES:"CHANGE_FIFTH_FORM_VALUES",
    CHANGE_SIXTH_FORM_VALUES:"CHANGE_SIXTH_FORM_VALUES",
    CHANGE_SEVENTH_FORM_VALUES:"CHANGE_SEVENTH_FORM_VALUES",
    CHANGE_SELECTED_FORM_STATE:"CHANGE_SELECTED_FORM_STATE",

}

export const PPRSecondFormActionTypes = {
    CHANGE_ESTATE_TYPE_STATE:"CHANGE_ESTATE_TYPE_STATE",
    CHANGE_ESTATE_CONDITION_STATE:"CHANGE_ESTATE_CONDITION_STATE",
    CHANGE_CITY_STATE:"CHANGE_CITY_STATE",
    CHANGE_STREET_STATE:"CHANGE_STREET_STATE",
    CHANGE_NUMBER_STATE:"CHANGE_NUMBER_STATE",
    CHANGE_FLOOR_STATE:"CHANGE_FLOOR_STATE",
    CHANGE_TOTAL_FLOORS_STATE:"CHANGE_TOTAL_FLOORS_STATE",
    CHANGE_ON_PILLARS_STATE:"CHANGE_ON_PILLARS_STATE",
    CHANGE_MAILING_LIST_STATE:"CHANGE_MAILING_LIST_STATE",
    CHANGE_SHOW_ERROR_STATE:"CHANGE_SHOW_ERROR_STATE",
    CHANGE_COMPLETED_STATE:"CHANGE_COMPLETED_STATE",
}

export const PPRThirdFormActionTypes = {
    CHANGE_ROOMS_STATE:"CHANGE_ROOMS_STATE",
    CHANGE_PARKING_STATE:"CHANGE_PARKING_STATE",
    CHANGE_BALCONIES_STATE:"CHANGE_BALCONIES_STATE",
    CHANGE_FEATURES_STATE:"CHANGE_FEATURES_STATE",
    CHANGE_DESCRIPTION_STATE:"CHANGE_DESCRIPTION_STATE",
    CHANGE_SHOW_ERROR_STATE:"CHANGE_SHOW_ERROR_STATE",
    CHANGE_COMPLETED_STATE:"CHANGE_COMPLETED_STATE",
}

export const PPRFourthFormActionTypes = {
    CHANGE_TOTAL_AREA_STATE:"CHANGE_TOTAL_AREA_STATE",
    CHANGE_BUILD_AREA_STATE:"CHANGE_BUILD_AREA_STATE",
    CHANGE_PRICE_STATE:"CHANGE_PRICE_STATE",
    CHANGE_ENTRY_DATE_STATE:"CHANGE_ENTRY_DATE_STATE",
    CHANGE_ENTRY_NOW_STATE:"CHANGE_ENTRY_NOW_STATE",
    CHANGE_ENTRY_FLEXIBLE_STATE:"CHANGE_ENTRY_FLEXIBLE_STATE",
    CHANGE_SHOW_ERROR_STATE:"CHANGE_SHOW_ERROR_STATE",
}

export const PPRSixthFormActionTypes = {
    CHANGE_CONTACT_NAME_STATE:"CHANGE_CONTACT_NAME_STATE",
    CHANGE_CONTACT_CELLPHONE_STATE:"CHANGE_CONTACT_CELLPHONE_STATE",
    CHANGE_CONTACT_VIRTUAL_CELLPHONE_STATE:"CHANGE_CONTACT_VIRTUAL_CELLPHONE_STATE",
    CHANGE_CONTACT_WEEKEND_STATE:"CHANGE_CONTACT_WEEKEND_STATE",
    CHANGE_CONTACT_EMAIL_STATE:"CHANGE_CONTACT_EMAIL_STATE",
    CHANGE_CONTACT_TERMS_STATE:"CHANGE_CONTACT_TERMS_STATE",
    CHANGE_CONTACT_MAILING_LIST_STATE:"CHANGE_CONTACT_MAILING_LIST_STATE",
    CHANGE_SHOW_ERROR_STATE:"CHANGE_SHOW_ERROR_STATE",
}