export const realestateSearchFormActionTypes = {
    CHANGE_TYPES_APARTMENTS_STATE:"CHANGE_TYPES_APARTMENTS_STATE",
    CHANGE_TYPES_HOUSES_STATE:"CHANGE_TYPES_HOUSES_STATE",
    CHANGE_TYPES_OTHERS_STATE:"CHANGE_TYPES_OTHERS_STATE",
    CHANGE_TYPES_ALL_STATE:"CHANGE_TYPE_ALL_STATE",
}