export const realestateSearchFormActionTypes = {
    CHANGE_TYPES_APARTMENTS_STATE:"CHANGE_TYPES_APARTMENTS_STATE",
    CHANGE_TYPES_HOUSES_STATE:"CHANGE_TYPES_HOUSES_STATE",
    CHANGE_TYPES_OTHERS_STATE:"CHANGE_TYPES_OTHERS_STATE",
    CHANGE_TYPES_ALL_STATE:"CHANGE_TYPE_ALL_STATE",
    CHANGE_ADDRESS_STATE:"CHANGE_ADDRESS_STATE",
    CHANGE_MAX_ROOMS_STATE:"CHANGE_MAX_ROOMS_STATE",
    CHANGE_MIN_ROOMS_STATE:"CHANGE_MIN_ROOMS_STATE",
    CHANGE_MIN_PRICE_STATE:"CHANGE_MIN_PRICE_STATE",
    CHANGE_MAX_PRICE_STATE:"CHANGE_MAX_PRICE_STATE",
}