const registrationFormActionTypes = {
    CHANGE_EMAIL_STATE:"CHANGE_EMAIL_STATE",
    CHANGE_PASSWORD_STATE:"CHANGE_PASSWORD_STATE",
    CHANGE_PASSWORD_REAPET_STATE:"CHANGE_PASSWORD_REAPET_STATE",
    CHANGE_FORM_MESSAGE_STATE:"CHANGE_FORM_ERROR_MESSAGE_STATE",
    CHANGE_SHOW_ERROR_MESSAGES_STATE:"CHANGE_SHOW_ERROR_MESSAGES_STATE",
}

export default registrationFormActionTypes;