const registrationSecondFormActionTypes = {
    CHANGE_NAME_STATE:"CHANGE_NAME_STATE",
    CHANGE_SURNAME_STATE:"CHANGE_SURNAME_STATE",
    CHANGE_CELLPHONE_STATE:"CHANGE_CELLPHONE_STATE",
    CHANGE_TERMS_STATE:"CHANGE_TERMS_STATE",
    CHANGE_MAILING_LIST_STATE:"CHANGE_MAILING_LIST_STATE",
    CHANGE_FORM_MESSAGE_STATE:"CHANGE_FORM_ERROR_MESSAGE_STATE",
    CHANGE_SHOW_ERROR_MESSAGES_STATE:"CHANGE_SHOW_ERROR_MESSAGES_STATE",
}

export default registrationSecondFormActionTypes;